### ISSUE TITLE
Would it be possible to implement MODBUS RTU rs485 

### ISSUE THREAD

**Issue by kevinterface** [cmbahadir/opcua-esp32#2]
I'm curious if the esp32 is capable of running a MODBUS RTU client beside the OPC UA server. The implementation of OPC UA is a great way to go directly from serial to a management network. 

Do you have any experience regarding the above?

**Comment by cmbahadir** [comment]
Hi @kevinterface 

I am not familiar with MODBUS. Do you mean MODBUS RTU Slave or MODBUS TCP/IP Client?

A MODBUS RTU over RS-485 slave implementation would be nice on ESP32 and seems like simpler but you need an additional hardware for RS-485 (like MAX485) and you MAY need to do few modifications on ESP32 -> MAX485 side to make it MODBUS compatible. 

The RS-485 example on ESP-IDF can be a good starting point;
https://github.com/espressif/esp-idf/tree/master/examples/peripherals/uart_echo_rs485

A MODBUS TCP/IP Client seems also possible, but not sure about a modbus server on esp32.

I found a modbus client example and a porting of freemodbus library to esp32;
FREEMODBUS - https://github.com/erfengwelink/modbus_port_esp32
MODBUS TCP/IP - https://github.com/bertmelis/esp32Modbus

Few benchmarks state that 100 register MODBUS RTU application requires 4kByte (8kByte with freemodbus library) of memory so it seems pretty light for ESP32 but as i said ı am not sure about industrial conformance of a MODBUS device and if esp meets the requirements or not.
