### ISSUE TITLE
Issue with building

### ISSUE THREAD

**Issue by zoran93** [cmbahadir/opcua-esp32#25]
Hi,
i have a problem with building the project.
The picture below shows the problem.
![Screenshot from 2020-04-20 08-56-57](https://user-images.githubusercontent.com/45490375/79947272-f6805d80-8471-11ea-9f96-85060a8dd935.jpg)

Maybe you know what could be wrong?

Best regards,

**Comment by cmbahadir** [comment]
Hi,

This is an issue with esp-idf, you can track the issue thread;
[https://github.com/espressif/esp-idf/issues/5046]

A workaround would be to use an older tag of esp-idf which dates back before the issue, and make a clean build afterwards.

**Comment by zoran93** [comment]
Thanks for your help.

Another thing, if you know from pratice. If I have one analog input, what is the maximum speed to upload the measured value to OPC-UA client? How fast is OPC-UA on esp32?

**Comment by cmbahadir** [comment]
I haven't tested the minimum sampling interval, but at least 1 s works for me. :) Please let me know when you try smaller values.  

I do not have a setup to test right now. Sorry about that.
