### ISSUE TITLE
About hardwave board type?

### ISSUE THREAD

**Issue by acer1204** [cmbahadir/opcua-esp32#26]
this project can build in ESP32-WROVER-B?

**Comment by cmbahadir** [comment]
It should work with wrover too. But i would suggest esp32-evb which is the one i have been using for development and the code is configured according to the relays over it.

https://www.olimex.com/Products/IoT/ESP32/ESP32-EVB/open-source-hardware

And it is also open hardware :) 
https://github.com/OLIMEX/ESP32-EVB
