### ISSUE TITLE
it not work in ESP32-WROVER?

### ISSUE THREAD

**Issue by acer1204** [cmbahadir/opcua-esp32#27]
i download this project and compile it success and download it in ESP32-WROVER-B.

it show emac_esp32_init rest timeout and init_mac failed.

is this problem is ESP32-WROVER just have wi-fi without eth?

![putty result](https://user-images.githubusercontent.com/6522774/83326455-b8632e80-a2a6-11ea-8fe7-e203708ba847.jpg)

**Comment by cmbahadir** [comment]
Is there any ethernet module on the board, and do you want to use it? 

If there is no physical ethernet configuration, the only choice is to use the WI-FI on ESP32, so you need to switch the config to use WiFi instead by changing the below line;

https://github.com/cmbahadir/opcua-esp32/blob/98c6ac288a431cfef1d5e374f283735d7d5076e2/components/ethernet/include/ethernet_connect.h#L19

to

`#define CONFIG_EXAMPLE_CONNECT_WIFI 1`

I will move these fields to sdkconfig in the future.

**Comment by acer1204** [comment]
> 板上是否有任何以太網模塊，您是否要使用它？
> 
> 如果沒有物理以太網配置，唯一的選擇是使用ESP32上的WI-FI，因此您需要通過更改以下行來切換配置以使用WiFi；
> 
> https://github.com/cmbahadir/opcua-esp32/blob/98c6ac288a431cfef1d5e374f283735d7d5076e2/components/ethernet/include/ethernet_connect.h#L19
> 
> 至
> 
> `#define CONFIG_EXAMPLE_CONNECT_WIFI 1`
> 
> 將來，我會將這些字段移至sdkconfig。

just replace "CONFIG_EXAMPLE_CONNECT_ETHERNET  1"  to "CONFIG_EXAMPLE_CONNECT_WIFI 1" and no other code needs to be changed in opcua-esp32 project?

**Comment by acer1204** [comment]
> Is there any ethernet module on the board, and do you want to use it?
> 
> If there is no physical ethernet configuration, the only choice is to use the WI-FI on ESP32, so you need to switch the config to use WiFi instead by changing the below line;
> 
> https://github.com/cmbahadir/opcua-esp32/blob/98c6ac288a431cfef1d5e374f283735d7d5076e2/components/ethernet/include/ethernet_connect.h#L19
> 
> to
> 
> `#define CONFIG_EXAMPLE_CONNECT_WIFI 1`
> 
> I will move these fields to sdkconfig in the future.

just replace "CONFIG_EXAMPLE_CONNECT_ETHERNET 1" to "CONFIG_EXAMPLE_CONNECT_WIFI 1" and no other code needs to be changed in opcua-esp32 project?

**Comment by cmbahadir** [comment]
After setting your wi-fi SSID and Password from `idf.py menuconfig`,  flash and run the `idf.py monitor`, the ip address after a succesful connection will appear on the log and you can connect from an OPC UA Client by using that IP address.

**Comment by acer1204** [comment]
> After setting your wi-fi SSID and Password from `idf.py menuconfig`, flash and run the `idf.py monitor`, the ip address after a succesful connection will appear on the log and you can connect from an OPC UA Client by using that IP address.

thank you very much!
It work Now.

**Comment by cmbahadir** [comment]
Your welcome, that would be great if you leave a star to the project. :)
