### ISSUE TITLE
anonymous 

### ISSUE THREAD

**Issue by velaspis** [cmbahadir/opcua-esp32#43]
hey I'm a beginner and I have a question 

how do you set the server to anonymous that you don't have to use username and password

**Comment by cmbahadir** [comment]
"SecurityPolicy#None" is set as default security policy of the server. So, it should not require a "Username" and "Password" when you try to connect from a client.

Security policy as none is set here by default; [UA_ServerConfig_setMinimalCustomBuffer](https://github.com/cmbahadir/opcua-esp32/blob/daba7cbed3c845f26bb8cb88a1f2cbcebea4eaf7/main/opcua_esp32.c#L81)
