### ISSUE TITLE
build with idf 5.0 error

### ISSUE THREAD

**Issue by legaxus** [cmbahadir/opcua-esp32#49]
### Occured on

- **opcua-esp32 branch/version/commit hash** : Which branch and commit you are using (simply write latest if it is the latest)
- **esp-idf tag/version/commit** : The value of 'git tag' in you esp-idf directory or provide the release version of it.
- **Hardware** : Type of the ESP32 development board you are using. (e.g. ESP32-EVB, ESP32-WROOM ...)
- **Your host OS** : Windows/Linux
  
### Description of problem
build with idf 5.0 error
![image](https://user-images.githubusercontent.com/122014240/215248551-2ff3ade2-fd28-4fca-98db-b7418a3eb8ab.png)
### Steps to Reproduce

1.
2.
3.

### Additional info 

Here please provide server logs with UA_LOGLEVEL=100 (if possible), wireshark traces or any kind of results from 'idf.py monitor'

**Comment by cmbahadir** [comment]
Please try running `idf.py fullclean` `idf.py menuconfig` first and then `idf.py build`.

**Comment by mural20** [comment]
Set CONFIG_ESP32_SPIRAM_SUPPORT to 0 and  it shall compile.

**Comment by legaxus-mis** [comment]
Got it compiled successfully, thanks.
